sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_TEST_COVERALLS=true
        - PATH="$HOME/.local/bin:$PATH"
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update php-coveralls/php-coveralls:2.0.0 ; fi

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer coveralls ; fi

notifications:
  email: true
